from app.schemas.analysis_job import AnalysisJobResponse, CreateAnalysisJobRequest
from app.schemas.analysis_debug import (
    AnalysisJobDebugResponse,
    BoundaryWarning,
    MockUsageRecord,
)
from app.schemas.common import new_id, utc_now
from app.services.observability_trace import build_debug_traces
from app.services.schema_validation_summary import build_schema_validation_records
from app.workflows.aesthetic_analysis_v1 import run_mock_aesthetic_analysis


class AnalysisJobService:
    def __init__(self, job_repository, input_repository, workflow_persistence) -> None:
        self.job_repository = job_repository
        self.input_repository = input_repository
        self.workflow_persistence = workflow_persistence

    def create_job(self, request: CreateAnalysisJobRequest) -> AnalysisJobResponse:
        now = utc_now()
        job = AnalysisJobResponse(
            id=new_id("job"),
            userId="user_anonymous",
            status="created",
            inputCount=len(request.input_ids),
            errorMessage=None,
            reportId=None,
            createdAt=now,
            startedAt=now,
            finishedAt=None,
        )
        self.job_repository.save(job)
        inputs = self.input_repository.get_many(request.input_ids)
        result = run_mock_aesthetic_analysis(job, inputs, self.workflow_persistence)
        return self.job_repository.save(result)

    def get_job(self, job_id: str) -> AnalysisJobResponse | None:
        return self.job_repository.get(job_id)

    def get_debug(self, job_id: str) -> AnalysisJobDebugResponse | None:
        job = self.job_repository.get(job_id)
        if job is None:
            return None

        logs = sorted(
            self.workflow_persistence.analysis_log_repository.get_for_job(job_id),
            key=lambda log: log.created_at,
        )
        schema_validation = build_schema_validation_records(logs)
        report = None
        if job.report_id is not None:
            report = self.workflow_persistence.report_repository.get(job.report_id)
        retrieval_trace, retrieval_items, context_assembly_trace, evaluation_trace = build_debug_traces(
            report,
            logs,
            schema_validation,
        )
        return AnalysisJobDebugResponse(
            jobId=job.id,
            status=job.status,
            workflowTrace=logs,
            fallbackEvents=[],
            mockUsage=_mock_usage(),
            schemaValidation=schema_validation,
            boundaryWarnings=_boundary_warnings(logs),
            retrievalTrace=retrieval_trace,
            retrievalItems=retrieval_items,
            contextAssemblyTrace=context_assembly_trace,
            evaluationTrace=evaluation_trace,
        )


def _mock_usage() -> list[MockUsageRecord]:
    return [
        MockUsageRecord(
            component="MockFeatureExtractor",
            status="enabled",
            devOnly=True,
            developerMessage="V1/V2 baseline uses mock or heuristic feature extraction; this is not a real vision model.",
        ),
        MockUsageRecord(
            component="MockEmbeddingClient",
            status="enabled",
            devOnly=True,
            developerMessage="Embedding values are deterministic mock vectors for schema and workflow validation.",
        ),
        MockUsageRecord(
            component="MockInterpretationGenerator",
            status="enabled",
            devOnly=True,
            developerMessage="Interpretations are generated by the local mock workflow and must not be treated as validated LLM output.",
        ),
    ]


def _boundary_warnings(logs) -> list[BoundaryWarning]:
    step_ids = {log.step_id for log in logs}
    history_status = "dev_only" if "retrieve_personal_history" in step_ids else "planned"
    history_message = (
        "V3-A personalized history retrieval is enabled for this workflow run."
        if history_status == "dev_only"
        else "Planned for V3 after V2 profile and feedback loops are stable."
    )
    knowledge_status = "dev_only" if "retrieve_aesthetic_knowledge" in step_ids else "planned"
    knowledge_message = (
        "V3-B aesthetic knowledge RAG is enabled for this workflow run."
        if knowledge_status == "dev_only"
        else "Planned for V3-B; external knowledge must remain explanation support only."
    )
    return [
        BoundaryWarning(
            capability="Real vision / LLM runtime",
            status="not_used",
            developerMessage="Current workflow uses mock or heuristic local components, not real model calls.",
        ),
        BoundaryWarning(
            capability="ChromaDB runtime writes",
            status="not_used",
            developerMessage="Current V2 keeps embedding metadata in application storage; ChromaDB runtime writes are not enabled.",
        ),
        BoundaryWarning(
            capability="Personalized history retrieval",
            status=history_status,
            developerMessage=history_message,
        ),
        BoundaryWarning(
            capability="Aesthetic knowledge RAG",
            status=knowledge_status,
            developerMessage=knowledge_message,
        ),
        BoundaryWarning(
            capability="Agent / MCP runtime",
            status="planned",
            developerMessage="Planned for V4; this iteration must not create Agent or MCP runtime behavior.",
        ),
    ]
