from app.schemas.analysis_job import AnalysisJobResponse, CreateAnalysisJobRequest
from app.schemas.analysis_debug import (
    AnalysisJobDebugResponse,
    BoundaryWarning,
    MockUsageRecord,
    SchemaValidationRecord,
)
from app.schemas.common import new_id, utc_now
from app.workflows.aesthetic_analysis_v1 import run_mock_aesthetic_analysis


class AnalysisJobService:
    def __init__(self, job_repository, input_repository, workflow_persistence) -> None:
        self.job_repository = job_repository
        self.input_repository = input_repository
        self.workflow_persistence = workflow_persistence

    def create_job(self, request: CreateAnalysisJobRequest) -> AnalysisJobResponse:
        now = utc_now()
        job = AnalysisJobResponse(
            id=new_id("job"),
            userId="user_anonymous",
            status="created",
            inputCount=len(request.input_ids),
            errorMessage=None,
            reportId=None,
            createdAt=now,
            startedAt=now,
            finishedAt=None,
        )
        self.job_repository.save(job)
        inputs = self.input_repository.get_many(request.input_ids)
        result = run_mock_aesthetic_analysis(job, inputs, self.workflow_persistence)
        return self.job_repository.save(result)

    def get_job(self, job_id: str) -> AnalysisJobResponse | None:
        return self.job_repository.get(job_id)

    def get_debug(self, job_id: str) -> AnalysisJobDebugResponse | None:
        job = self.job_repository.get(job_id)
        if job is None:
            return None

        logs = sorted(
            self.workflow_persistence.analysis_log_repository.get_for_job(job_id),
            key=lambda log: log.created_at,
        )
        return AnalysisJobDebugResponse(
            jobId=job.id,
            status=job.status,
            workflowTrace=logs,
            fallbackEvents=[],
            mockUsage=_mock_usage(),
            schemaValidation=_schema_validation(logs),
            boundaryWarnings=_boundary_warnings(),
        )


def _mock_usage() -> list[MockUsageRecord]:
    return [
        MockUsageRecord(
            component="MockFeatureExtractor",
            status="enabled",
            devOnly=True,
            developerMessage="V1/V2 baseline uses mock or heuristic feature extraction; this is not a real vision model.",
        ),
        MockUsageRecord(
            component="MockEmbeddingClient",
            status="enabled",
            devOnly=True,
            developerMessage="Embedding values are deterministic mock vectors for schema and workflow validation.",
        ),
        MockUsageRecord(
            component="MockInterpretationGenerator",
            status="enabled",
            devOnly=True,
            developerMessage="Interpretations are generated by the local mock workflow and must not be treated as validated LLM output.",
        ),
    ]


def _schema_validation(logs) -> list[SchemaValidationRecord]:
    logs_by_step = {log.step_id: log for log in logs}
    schema_steps = [
        ("extract_features", "InputFeature"),
        ("generate_embeddings", "EmbeddingRecord"),
        ("cluster_inputs", "SimilarityGroup / PossibleInterpretation / Insight"),
        ("generate_report", "ReportResponse"),
        ("save_report", "PersistenceWrite"),
    ]
    records: list[SchemaValidationRecord] = []
    for step_id, schema_name in schema_steps:
        log = logs_by_step.get(step_id)
        if log is None:
            status = "not_recorded"
            message = "No workflow log was recorded for this schema boundary."
        elif log.status == "success":
            status = "passed"
            message = "Workflow step completed and produced data accepted by the current schema boundary."
        else:
            status = "failed"
            message = log.error_message or "Workflow step failed before schema output was accepted."
        records.append(
            SchemaValidationRecord(
                stepId=step_id,
                schemaName=schema_name,
                status=status,
                developerMessage=message,
            )
        )
    return records


def _boundary_warnings() -> list[BoundaryWarning]:
    return [
        BoundaryWarning(
            capability="Real vision / LLM runtime",
            status="not_used",
            developerMessage="Current workflow uses mock or heuristic local components, not real model calls.",
        ),
        BoundaryWarning(
            capability="ChromaDB runtime writes",
            status="not_used",
            developerMessage="Current V2 keeps embedding metadata in application storage; ChromaDB runtime writes are not enabled.",
        ),
        BoundaryWarning(
            capability="Personalized retrieval / RAG",
            status="planned",
            developerMessage="Planned for V3 after V2 profile and feedback loops are stable.",
        ),
        BoundaryWarning(
            capability="Agent / MCP runtime",
            status="planned",
            developerMessage="Planned for V4; this iteration must not create Agent or MCP runtime behavior.",
        ),
    ]
